pipeline {
    agent {
        label 'ec2-agent'
    }

    environment {
        SWARM_MANAGER = "ubuntu@<private-ip>"
    }

    stages {
        stage('Network Debug') {
            steps {
                sh '''
                echo "===== WHOAMI ====="
                whoami

                echo "===== HOSTNAME ====="
                hostname

                echo "===== PRIVATE IP ====="
                curl -s http://169.254.169.254/latest/meta-data/local-ipv4

                echo "===== TEST SSH ====="
                nc -zv <swarm-manager-private-ip> 22
                '''
            }
        }

        stage('Deploy to Swarm') {
            steps {
                sshagent(['swarm-master']) {
                    sh """
                        scp -o StrictHostKeyChecking=no stack.yml ${SWARM_MANAGER}:~/stack.yml

                        ssh -o StrictHostKeyChecking=no ${SWARM_MANAGER} '
                            docker stack deploy -c ~/stack.yml app
                        '
                    """
                }
            }
        }
    }
}
