version: "3.8"

services:

  frontend:
    image: vaibhavu8485/frontend:latest
    ports:
      - "80:80"
    networks:
      - app-net

  backend:
    image: vaibhavu8485/backend:latest
    ports:
      - "3000:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: overlay